//
// Generated file, do not edit! Created by nedtool 4.6 from GreedyPlusPkt.msg.
//

#ifndef _GREEDYPLUSPKT_M_H_
#define _GREEDYPLUSPKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "NetwPkt_m.h"
#include "GeoNode.h"
// }}

/**
 * Class generated from <tt>GreedyPlusPkt.msg:10</tt> by nedtool.
 * <pre>
 * message GreedyPlusPkt extends NetwPkt
 * {
 *     GeoNode destNode;
 *     GeoNode interNode;
 *     GeoNode route[];
 *     double length = 0;
 *     double baseLineFactor[3];
 * }
 * </pre>
 */
class GreedyPlusPkt : public ::NetwPkt
{
  protected:
    GeoNode destNode_var;
    GeoNode interNode_var;
    GeoNode *route_var; // array ptr
    unsigned int route_arraysize;
    double length_var;
    double baseLineFactor_var[3];

  private:
    void copy(const GreedyPlusPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GreedyPlusPkt&);

  public:
    GreedyPlusPkt(const char *name=NULL, int kind=0);
    GreedyPlusPkt(const GreedyPlusPkt& other);
    virtual ~GreedyPlusPkt();
    GreedyPlusPkt& operator=(const GreedyPlusPkt& other);
    virtual GreedyPlusPkt *dup() const {return new GreedyPlusPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual GeoNode& getDestNode();
    virtual const GeoNode& getDestNode() const {return const_cast<GreedyPlusPkt*>(this)->getDestNode();}
    virtual void setDestNode(const GeoNode& destNode);
    virtual GeoNode& getInterNode();
    virtual const GeoNode& getInterNode() const {return const_cast<GreedyPlusPkt*>(this)->getInterNode();}
    virtual void setInterNode(const GeoNode& interNode);
    virtual void setRouteArraySize(unsigned int size);
    virtual unsigned int getRouteArraySize() const;
    virtual GeoNode& getRoute(unsigned int k);
    virtual const GeoNode& getRoute(unsigned int k) const {return const_cast<GreedyPlusPkt*>(this)->getRoute(k);}
    virtual void setRoute(unsigned int k, const GeoNode& route);
    virtual double getLength() const;
    virtual void setLength(double length);
    virtual unsigned int getBaseLineFactorArraySize() const;
    virtual double getBaseLineFactor(unsigned int k) const;
    virtual void setBaseLineFactor(unsigned int k, double baseLineFactor);
};

inline void doPacking(cCommBuffer *b, GreedyPlusPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GreedyPlusPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _GREEDYPLUSPKT_M_H_

